version: '3'

services:
  api:
    image: strapi/strapi
    container_name: healthdesk-api
    environment:
      - APP_NAME=healthdesk-back
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=healthdesk
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ~/healthdesk-back/strapi:/usr/src/api/healthdesk-back
      #- /usr/src/api/healthdesk-back/node_modules
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    container_name: healthdesk-db
    environment:
      - MONGO_INITDB_DATABASE=healthdesk
    ports:
      - 27017:27017
    volumes:
      - ~/healthdesk-back/db:/data/db
    restart: always